apiVersion: "v1"
kind: Pod
metadata:
  name: python-track-web
  labels:
    name: web
    app: python-track-app
spec:
  containers:
    - name: web
      image: docker-python-app
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP
