apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: python-track-web
    app: docker-python-app
spec:
  selector:
    name: python-web
  type: NodePort
  ports:
   - port: 80
     targetPort: 5000
     protocol: TCP
